### PR TITLE
added ruby-3.1 compatibility

### PR DESCRIPTION
**Pull request by skunkworker**
Specs work on:

Jruby 9.3/9.4
CRuby 2.7/3.0/3.1

after the arguments change.

### CODE REVIEW

**Comment by skunkworker** [comment]
I'll get multiple rails support testing up soon.

**Review by liveh2o — APPROVED** [review]

**Comment by liveh2o** [comment]
Released in [v7.0.0](https://github.com/liveh2o/active_remote/releases/tag/v7.0.0).

**Comment by liveh2o** [comment]
I'm guessing merging this and #96 changed something because actions are now failing... 🤔

**Comment by skunkworker** [comment]
@liveh2o I think we need to make a separate 6-1-stable branch with includes Ruby 3.1 support. As the newest Rails 7 release is pinned pessimistically to `~> 7.0`. And I am currently in the process of taking a Rails 6.1 app to JRuby-9.4 (3.1 syntax) and there is no version that supports that at this time.

**Comment by liveh2o** [comment]
> @liveh2o I think we need to make a separate 6-1-stable branch with includes Ruby 3.1 support. As the newest Rails 7 release is pinned pessimistically to `~> 7.0`. And I am currently in the process of taking a Rails 6.1 app to JRuby-9.4 (3.1 syntax) and there is no version that supports that at this time.

Ah, I see. I backported this change to v6.1.2. Specs pass under Ruby 2.7, so we should be good to go. Let me know if you have issues.

**Comment by liveh2o** [comment]
I also backported this change to v6.0.3 even though Rails 6.0 is EOL.

**Pull request merged**
